routes:
    home:           'Default:home'
    uploadFile:     'File:uploadFile'
    renameFile:     'File:renameFile'
    replaceFile:    'File:replaceFile'
    deleteFile:     'File:deleteFile'
    moveFile:       'File:moveFile'
    createFolder:   'Folder:createFolder'
    login:          'Security:login'
    logout:         'Security:logout'
    register:       'Security:register'
    profile:        'Profile:profile'  

default_route: 'home'

db_config:
    name: 'filer3'
    host: 'localhost'
    user: 'root'
    pass: 'root'
