routes:
    home:           'Default:home'
    login:          'Security:login'
    logout:         'Security:logout'
    register:       'Security:register'
    profile:        'Profile:profile'

default_route: 'home'

db_config:
    name: 'filer3'
    host: 'localhost'
    user: 'root'
    pass: 'root'
